config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do 
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:show, :create] do
      member do
        post "downvote"
        post "upvote"
      end
    end
  root to: redirect("/subs")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Votable
  validates :content, :author, :post, presence: true
  belongs_to :post, inverse_of: :comments
  belongs_to :author, class_name: "User", foreign_key: :author_id, inverse_of: :comments
  belongs_to :parent_comment, class_name: "Comment", foreign_key: :parent_comment_id
  has_many( 
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: :show
  
  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    post_id = @comment.post_id
    if @comment.save
      redirect_to post_url(post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(post_id)
    end
  end
  
  def show
    @comment = Comment.find(params[:id])
    @new_comment = Comment.new(
      post_id: @comment.post_id, parent_comment_id: @comment.id
    )
    render :show
  end
  
  def downvote; vote(-1); end
  def upvote; vote(1); end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
  
  def vote(dir)
    @comment = Comment.find(params[:id])
    @user_vote = UserVote.find_by(
      votable_id: @comment.id, votable_type: "Comment", user_id: current_user.id
    )

    if @user_vote
      @user_vote.update(value: dir)
    else
      @comment.user_votes.create!(
        user_id: current_user.id, value: dir
      )
    end

    redirect_to post_url(@comment.post)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_comment.html.erb
<p>
	<%= comment.votes %>
  <%= link_to comment.content, comment_url(comment.id) %>
	<%= button_to "Upvote", upvote_comment_url(comment) %>
	<%= button_to "Downvote", downvote_comment_url(comment) %>
</p>

<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.parent_comment_id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <textarea name="comment[content]"><%= @comment.content %></textarea>
  <br>
  <input type="submit" value="Submit" id="postmit">
</form>

app/views/comments/new.html.erb
<h1>New Comment!</h1>

<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<%= @comment.votes %>
<%= @comment.content %> by <%= @comment.author.username %>
<br><br>

<b>Reply to this comment:</b>
<%= render "form", comment: @new_comment %>