config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do 
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:show, :create] do
      member do
        post "downvote"
        post "upvote"
      end
    end
  root to: redirect("/subs")
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  include Votable
  validates :title, :moderator, :description, presence: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id
  )
  
  has_many :sub_posts, inverse_of: :sub
  has_many :posts, through: :sub_posts, source: :post
  
end

app/controllers/subs_controller.rb
 class SubsController < ApplicationController
  before_action :require_login
  
  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit  
    @sub = Sub.find(params[:id])
    redirect_to subs_path unless user_is_creator?(@sub, :moderator_id)
  end

  def update
    @sub = Sub.find(params[:id])
    redirect_to subs_path unless user_is_creator?(@sub, :moderator_id)
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end  
  end
  
  def downvote; vote(-1); end
  def upvote; vote(1); end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
  def vote(dir)
    @sub = Sub.find(params[:id])
    @user_vote = UserVote.find_by(
      votable_id: @sub.id, votable_type: "Sub", user_id: current_user.id
    )

    if @user_vote
      @user_vote.update(value: dir)
    else
      @sub.user_votes.create!(
        user_id: current_user.id, value: dir
      )
    end

    redirect_to sub_url(@sub)
  end 
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>Edit a Sub</h1>
<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
	 <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="title">Title</label><input type="text" name="sub[title]" value="<%= @sub.title %>" id="title">
  <label for="description">Description</label><input type="text" name="sub[description]" value="<%= @sub.description %>" id="description">
  <input type="submit" name="some_name" value="Submit" id="submit">
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
<% @subs.each do |sub| %>
  <%= sub.votes %>
  <%= link_to sub.title, sub_url(sub) %>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a Sub</h1>
<form action="<%= subs_url %>" method="POST">
	 <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="title">Title</label><input type="text" name="sub[title]" value="<%= @sub.title %>" id="title">
  <label for="description">Description</label><input type="text" name="sub[description]" value="<%= @sub.description %>" id="description">
  <input type="submit" name="some_name" value="Submit" id="submit">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h1><%= @sub.votes %></h1>
Description
<h2><%= @sub.description %></h2>
<%= button_to "Upvote", upvote_sub_url(@sub) %>
<%= button_to "Downvote", downvote_sub_url(@sub) %>

<% if user_is_creator?(@sub, :moderator_id)%>
  <%= link_to "Edit", edit_sub_url(@sub) %>
<%end%>

<%= link_to "Make New Post!", new_post_url %>

<ul>
  <% @sub.posts.each do |post| %>
    <li>(<%= post.votes %>) <%= link_to post.title, post %>
			<%= button_to "Upvote", upvote_post_url(post) %>
			<%= button_to "Downvote", downvote_post_url(post) %>
		</li>
  <% end %>
</ul>