config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do 
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:show, :create] do
      member do
        post "downvote"
        post "upvote"
      end
    end
  root to: redirect("/subs")
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Votable
  validates :title, :author, presence: true
  
  belongs_to :author, class_name: "User"  
  has_many :sub_posts, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :sub_posts, source: :sub
  has_many :comments, inverse_of: :post
  
  has_many(
      :top_level_comments,
      -> { where("parent_comment_id IS NULL") },
      class_name: "Comment"
  )
  
  def comments_by_parent
    results = Hash.new { |hash, key| hash[key] = [] }

    self.comments.includes(:author).each do |comment|
      results[comment.parent_comment_id] << comment
    end

    results
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: :show
  before_action :require_user_being_creator, only: [:edit, :update, :destroy]
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors
      render :update
    end
  end
  
  def downvote; vote(-1); end
  def upvote; vote(1); end
  
  private
    def post_params
      params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end
    
    def require_user_being_creator
      @post = Post.find(params[:id])
      redirect_to subs_path unless user_is_creator?(@post, :author_id)
    end
    
    def vote(dir)
      @post = Post.find(params[:id])
      @user_vote = UserVote.find_by(
        votable_id: @post.id, votable_type: "Post", user_id: current_user.id
      )

      if @user_vote
        @user_vote.update(value: dir)
      else
        @post.user_votes.create!(
          user_id: current_user.id, value: dir
        )
      end

      redirect_to post_url(@post)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
  <h1>Edit a post</h1>
  <form action="<%= post_url(@post) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
		  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <% Sub.all.each do |sub| %>
       <input <%="checked" if @post.sub_ids.include?(sub.id)%> type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>">
       <label><%=sub.title %></label>
    <% end %>
    <br>
    <label for="title">Title</label><input type="text" name="post[title]" value="<%= @post.title %>" id="title">
    <br>
    <label for="url">URL</label><input type="text" name="post[url]" value="<%= @post.url %>" id="url">
    <br>
    <label for="content">Content</label>
    <textarea name="post[content]"><%= @post.content %></textarea>
    <br>
    <input type="submit" name="some_name" value="Submit" id="postmit">
  </form>
  
  

app/views/posts/new.html.erb
  <h1>Create a post</h1>
  <form action="<%= posts_url %>" method="POST">
		  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <% Sub.all.each do |sub| %>
       <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>">
       <label><%=sub.title %></label>
    <% end %>
    <br>
    <label for="title">Title</label><input type="text" name="post[title]" value="<%= @post.title %>" id="title">
    <br>
    <label for="url">URL</label><input type="text" name="post[url]" value="<%= @post.url %>" id="url">
    <br>
    <label for="content">Content</label>
    <textarea name="post[content]"><%= @post.content %></textarea>
    <br>
    <input type="submit" name="some_name" value="Submit" id="postmit">
  </form>
  

app/views/posts/show.html.erb
<h1><%= @post.title %> by <%= @post.author.username %></h1> 
<h1><%= @post.votes %></h1>
<h3><%= link_to(@post.url) if @post.url %></h3>
<br>
Content
<p><%= @post.content if @post.content %></p>
<%= button_to "Upvote", upvote_post_url(@post) %>
<%= button_to "Downvote", downvote_post_url(@post) %>
<br><br>
Subs
<ul>
  <% @post.subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>
<% if user_is_creator?(@post, :author_id)%>
  <%= link_to "Edit", edit_post_url(@post) %>
<% end %>

<h2>Comments</h2>

<%= link_to "Comment on this post!", new_post_comment_url(@post.id) %>
<br><br>

<ul>
  <% comments_by_parent = @post.comments_by_parent %>
  <% comments_by_parent[nil].each do |top_level_comment| %>
    <li>
      <%= render("comments/comment",
                 comment: top_level_comment,
                 comments_by_parent: comments_by_parent) %>
    </li>
  <% end %>
</ul>